name: Deploy to HuggingFace Spaces

on:
  workflow_run:
    workflows:
      - "Python application" 
    types:
      - completed
  workflow_dispatch:
permissions:
  contents: read

jobs:
   build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Push to Hugging Face Space
      env:
        HF_TOKEN: ${{ secrets.HF }}
      run: |
       pip install -U "huggingface_hub[cli]"
       huggingface-cli login --token $HF_TOKEN --add-to-git-credential
    - run: make upload

